### ISSUE TITLE
[EN]🧐Possible Some spelling error, missing comma, and etc.

### ISSUE THREAD

**Issue by JonathanSum** [Atcold/pytorch-Deep-Learning#402]
![image](https://user-images.githubusercontent.com/21982975/86761921-282dad00-bffb-11ea-87fb-c4c946f6009c.png)

![image](https://user-images.githubusercontent.com/21982975/86665952-f853ba80-bfa4-11ea-9c05-82715272d21a.png)
blue points?
![image](https://user-images.githubusercontent.com/21982975/86666000-043f7c80-bfa5-11ea-92a2-102155100219.png)
![image](https://user-images.githubusercontent.com/21982975/86666023-099cc700-bfa5-11ea-87d9-e61e42961db4.png)

![image](https://user-images.githubusercontent.com/21982975/86762761-b6a22e80-bffb-11ea-969e-938093081a80.png)

![image](https://user-images.githubusercontent.com/21982975/86666082-16b9b600-bfa5-11ea-9f46-ab76a080c854.png)
![image](https://user-images.githubusercontent.com/21982975/86666154-26d19580-bfa5-11ea-974d-cb15b5138a65.png)

![image](https://user-images.githubusercontent.com/21982975/86666191-2fc26700-bfa5-11ea-9099-f6745e11cfcc.png)
In L2, the erros...
If you feel some of them are fine, please feel free to ignore it and close it.
However, if some of them need to be fixed and some of ppl are going to do it, please feel free to them and close it.

**Comment by Atcold** [comment]
![image](https://user-images.githubusercontent.com/2119355/87123014-f400f900-c253-11ea-85fe-8799b160fb7a.png)

🤣🤣🤣

**Comment by Atcold** [comment]
> ![image](https://user-images.githubusercontent.com/21982975/86761921-282dad00-bffb-11ea-87fb-c4c946f6009c.png)

What's up? What's that red bar?

> ![image](https://user-images.githubusercontent.com/21982975/86665952-f853ba80-bfa4-11ea-9c05-82715272d21a.png)
> blue points?

Yes, *point<ins>s</ins>*.

> ![image](https://user-images.githubusercontent.com/21982975/86666000-043f7c80-bfa5-11ea-92a2-102155100219.png)

- […] taking successful attempts **,** is […]
- [Wu, Xiong, Yu, Lin (2018) Unsupervised feature learning via non-parametric instance discrimination](https://arxiv.org/abs/1805.01978).

> ![image](https://user-images.githubusercontent.com/21982975/86666023-099cc700-bfa5-11ea-87d9-e61e42961db4.png)

- […] second contrastive <ins>term</ins> […]
- By <ins>transitivity</ins>, […]
- […] for separating this <ins>out was that it</ins> stabilized training […]
- Evaluation can be performed by full fine-tuning (initialisation evaluation) or training a linear classifier (feature evaluation).
- PIRL robustness has been tested by using images in-distribution by training it on in-the-wild images.

This student just use the automated captions generated by Zoom. Probably because s/he did not understand what was going on in class.

> ![image](https://user-images.githubusercontent.com/21982975/86762761-b6a22e80-bffb-11ea-969e-938093081a80.png)

Looks okay to me.

> ![image](https://user-images.githubusercontent.com/21982975/86666082-16b9b600-bfa5-11ea-9f46-ab76a080c854.png)

[…] other <ins>pretext</ins> tasks […]

> ![image](https://user-images.githubusercontent.com/21982975/86666154-26d19580-bfa5-11ea-974d-cb15b5138a65.png)

Yes?

> ![image](https://user-images.githubusercontent.com/21982975/86666191-2fc26700-bfa5-11ea-9099-f6745e11cfcc.png)
> In L2, the erros...
> If you feel some of them are fine, please feel free to ignore it and close it.
> However, if some of them need to be fixed and some of ppl are going to do it, please feel free to them and close it.

Yes, the comma is missing.

Please, feel free to send a PR with these corrections!
Thank you so much for spotting these typos! I did not have the time to read everything though. I've mostly skimmed these contributions, and I'm still behind with the video editing process.

**Comment by JonathanSum** [comment]
In model, distillation
![image](https://user-images.githubusercontent.com/21982975/87145014-88238e00-c25d-11ea-833d-ab2dcc681620.png)
PIRL was actually on **part**?
![image](https://user-images.githubusercontent.com/21982975/87145209-d042b080-c25d-11ea-99a1-b22e5d738998.png)
For the one that has rectification and parametrising is fine. It was my mistake to post it here.

**Comment by Atcold** [comment]
@JonathanSum, can you fix these issues on the English version and send a PR?

**Comment by JonathanSum** [comment]
@Atcold Of course, I closed it because I was about to fix this issue and send a PR. I sent the PR few hours later. 

Again, thanks for sharing the course anyway.😋

**Comment by JonathanSum** [comment]
@Atcold 
Of course, I have sent a PR 1 day ago.

**Comment by Atcold** [comment]
Awesome! You can close an issue by typing

> Close #402

or 

> Fix #402

Anyhow, thanks for your contribution!
