### ISSUE TITLE
[FR] README-FR.md

### ISSUE THREAD

**Issue by AliEl-01** [Atcold/pytorch-Deep-Learning#620]
i'm confused a little bit !!! in (https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/fr/README-FR.md) i see both languages '_ENGLISH_' and '_FRENSH_' 

![both](https://user-images.githubusercontent.com/58257628/94069584-c0605480-fde8-11ea-8bd3-0f6559b4d4b8.PNG)

**Comment by lbourdois** [comment]
The tags used to comment on English texts have been badly generated so we still see English. This will be fixed with my next PR which has to correct the WIP files of the Wiki (https://github.com/Atcold/pytorch-Deep-Learning/wiki/French-translation).
Please read the instructions in the Wiki : **only files where "Translation status" is OK can be reviewed** (currently weeks 1 to 12).  **Files where the "Translation status" says "WIP" (such as the README file) are always worked on**. It is therefore useless to review them since they are not finished.

If you are interested in the review in French, you can ask your questions in the dedicated slack channel.

**Comment by Atcold** [comment]
Thanks @AliEl-01 for catching this!

**Comment by AliEl-01** [comment]
@lbourdois sorry I didn't read the instructions in the wiki page😄😄
